# Enter GitHub API OAuth token (or personal access token)
# to increase the requests limit from 60 to 5000 per hour.
token: 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
---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8080
url: http://localhost:8080
---
spring:
  config:
    activate:
      on-profile: prod
url: https://arturkolaska.herokuapp.com